### ISSUE TITLE
Fase de análisis, diseño

### ISSUE THREAD

**Issue by piter1902** [UNIZAR-30226-2020-01/backend_django#1]
Plantear el esquema E/R.
Realizar el modelo en Django.
Elegir el **cloud** a utilizar.
Elegir el SGBD a utilizar.
Realizar un diagrama de despliegue **REAL**.
Realizar un despliegue en Docker.

**Comment by nestor98** [comment]
~~Plantear el esquema E/R.~~
~~Realizar el modelo en Django.~~
Elegir el cloud a utilizar.
Elegir el SGBD a utilizar. -> SQLDBM?
Realizar un diagrama de despliegue REAL.
Realizar un despliegue en Docker.

**Comment by nestor98** [comment]
Análisis de requisitos detallado
Actualizar E-R, relacional, BD (con django y makemigrations, migrate)

Elegir el cloud a utilizar.
