### ISSUE TITLE
Arreglar problema: number_songs de cada album no aparece en la vista de lista del artista.

### ISSUE THREAD

**Issue by piter1902** [UNIZAR-30226-2020-01/backend_django#16]

**Comment by jtambo99** [comment]
Bug arreglado

**Comment by piter1902** [comment]
No aparecen.

**Comment by nestor98** [comment]
Sí aparecen. number_songs al final del todo, junto con number_albums

**Comment by piter1902** [comment]
En este [enlace](https://i.imgur.com/tHvLBJt.png) se puede ver como no aparece el número de canciones de cada album en la "vista de lista del album" **dentro** de la vista de lista del artista (en _/artists/_).

**Comment by piter1902** [comment]
Arreglado.
