### ISSUE TITLE
El serializador de la vista de lista de album en /artists/:id/ tiene campo songs.

### ISSUE THREAD

**Issue by piter1902** [UNIZAR-30226-2020-01/backend_django#28]
Esto no debería ser así ya que no lo estamos utilizando en ese punto y puede ocasionar problemas de rendimiento.

**Comment by nestor98** [comment]
Ni idea de en que momento cambiamos eso, pero arreglado con 98bfc29d5d1df274cf487f3a8be6a5e0ee1e59b7
