### ISSUE TITLE
Creo que falta añadir seguir una playlist y seguir podcast, no?

### ISSUE THREAD

**Issue by jtambo99** [UNIZAR-30226-2020-01/backend_django#42]

**Comment by nestor98** [comment]
Lo de podcasts no serían las suscripciones? Y de las playlists desde la última versión el RF15 es este, que ya está implementado:
El sistema permitirá la gestión de amigos y compartir listas de reproducción entre los
mismos. Concretamente, un usuario puede seguir a otros, lo que le permitirá ver las listas de reproducción de estos.

**Comment by jtambo99** [comment]
Lo de playlist esta implementado. Falta (creo) añadir un podcast a un user.

**Comment by jtambo99** [comment]
Finalizado.
