### ISSUE TITLE
APIs de Podcasts

### ISSUE THREAD

**Issue by nestor98** [UNIZAR-30226-2020-01/backend_django#5]
Investigar e implementar la subscripción y gestión de podcasts con Python.

**Comment by nestor98** [comment]
[Listennotes](https://www.listennotes.com/api/docs/) parece la api mas usada. Hay que hacerse cuenta, que lleva bastantes pasos, pero es gratis. 
Con la cuenta gratis tienes 10.000 peticiones al mes, tenemos que poner su logo en alguna parte y no podemos guardar metadatos en la bd, pero yo creo que de momento nos vale

**Comment by nestor98** [comment]
Podriamos usar un lector de RSS como [este](https://github.com/xurble/django-feed-reader), que tiene hasta alguna funcionalidad especifica para podcasts!

**Comment by jtambo99** [comment]
Por el momento ya tenemos hechas las consultas a listennotes
